runtime: java17
instance_class: F2

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
